POST http://localhost:3003/api/blogs
Content-Type: application/json

{
    "title" : "New article from Belfast",
    "author" : "Nicole Formenti-Pedroia",
    "url": "nick.com",
    "likes": 1
}

###
GET  http://localhost:3003/api/blogs
